# See: https://dart.dev/tools/pub/pubspec
name: dogma
version: 1.0.0
description: >-
  Dogma for Dart.
homepage: https://github.com/dogmatists/dogma.dart
repository: https://github.com/dogmatists/dogma.dart
issue_tracker: https://github.com/dogmatists/dogma.dart/issues
documentation:
dependencies:
dev_dependencies:
  pedantic: '>=1.10.0'
  test: any
dependency_overrides:
environment:
  sdk: '>=2.12.0 <3.0.0'
executables:
